# 🧠 NEURONVAULT - ANALYSIS OPTIONS (FREEZED COMPATIBLE)
# Configured to work with Freezed without analyzer conflicts

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"

  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

  errors:
    # Ignore common Freezed/generated code issues
    invalid_annotation_target: ignore
    undefined_prefixed_name: ignore

    # Ignore analyzer conflicts
    analyzer_use_new_elements: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore

    # Allow generated code patterns
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore

linter:
  rules:
    # Disable rules that conflict with Freezed
    avoid_annotating_with_dynamic: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false

    # Keep essential rules
    prefer_single_quotes: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors_in_immutables: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true